### PR TITLE
Make the game

### PR DESCRIPTION
**Pull request by lislis**
Very wip

@ramonh sorry this takes so long! I hope I can finish the prototype this week and then break it down into sensible steps for the workshop

### CODE REVIEW

**Comment by hola-soy-milk** [comment]
Please don't apologize @lislis I'll go ahead and give it a try :)

**Comment by lislis** [comment]
@ramonh it's not like it's playable yet. but it should compile and some things should move :D

**Comment by hola-soy-milk** [comment]
Omg

I LOVE the graphics :D:DD:D:D

**Comment by hola-soy-milk** [comment]
Thanks! Everything looks solid 🎉

**Pull request merged**
